version: "3"
services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "5002:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./bd_init:/docker-entrypoint-initdb.d/:ro
  app:
    build: ./app
    ports:
      - "5000:5000"
    links:
      - db