version: '3'
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - '5000:5000'
  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    expose:
      - '3306'