version: "3"
services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    links:
      - db
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "5001:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"